### ISSUE TITLE
Don't work in Internet Explorer 11

### ISSUE THREAD

**Issue by imkremen** [Diokuz/baron#106]
Internet Explorer 11. Windows 8.1
See image:
![capture](https://cloud.githubusercontent.com/assets/4233786/10910332/8809f69e-8247-11e5-9602-c8eb670c6364.PNG)

**Comment by Diokuz** [comment]
Really strange picture. On the right container there must be only horizontal scroll, even if native.

Cannot reproduce on win7 ie10, will try win8.

**Comment by Diokuz** [comment]
Cannot reproduce.
I think JavaScript is disabled in your ie11 (bar is invisible). Turn js on.
Will update demo to hide custom track too.
