### ISSUE TITLE
No jQuery?

### ISSUE THREAD

**Issue by Diokuz** [Diokuz/baron#131]
I have written jQuery-like utility in react-baron [here](https://github.com/Diokuz/react-baron/blob/master/index.js). Its about 431 bytes gzip.

Does anybody hate jQuery and want that utility in baron?

Note, that baron already have `$` and `event` param.
# 

Я запилил в react-baron [заменитель](https://github.com/Diokuz/react-baron/blob/master/index.js) jQuery, который после gzip весит 431 байт. Если этот код занести в этот репозиторий, можно будет вообще забить на jQuery. Кому-нибудь это надо?

431 вроде не много, но и лишнего тянуть не хочется. Тем более, что в бароне уже есть возможность передачи параметров $ и event.

**Comment by notiv-nt** [comment]
2016 пора бы потихоньку забывать о jQuery ?

**Comment by SE-Yari** [comment]
Я за!

**Comment by Diokuz** [comment]
Fixed in baron@3.0.0
