### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by antelle** [Diokuz/baron#132]
[Here](https://github.com/Diokuz/baron/blob/master/src/core.js#L10) you have instances array, and actually instances are only [pushed](https://github.com/Diokuz/baron/blob/master/src/core.js#L358) to it and not removed on [dispose](https://github.com/Diokuz/baron/blob/master/src/core.js#L173). The element is still referenced from instance, and this leads to memory leak.
In my app, I've noticed that subsequent inits and disposes don't free consumed resources and resolved it with removing from `baron._instances`.
Please consider removing from instances on `dispose` call.

**Comment by Diokuz** [comment]
Thanks! It seems reasonable.
