### ISSUE TITLE
Инициализация барона без jQuery

### ISSUE THREAD

**Issue by uaNikita** [Diokuz/baron#140]
Расскажите как правильно инициализировать baron без jQuery? Не получилось разобраться.

**Comment by Diokuz** [comment]
Нужно вызывать baron как глобальную функцию, и обязательно передавать ему параметр `scroller`, `event` и `$`. Про них можно почитать в разделе [API](https://github.com/Diokuz/baron/blob/master/docs/api.md).

Много примеров есть в [тестах](https://github.com/Diokuz/baron/blob/master/test/nojqueryTests.js).

**Comment by vykulakov** [comment]
Ещё есть [страничка](https://github.com/Diokuz/baron/blob/master/docs/logs/no-jquery-detected.md) с описанием запуска без jQuery. Правда, если делать по ней, то прокрутка перетаскиванием бара не работает.

В итоге, если делать без jQuery, то общее количество необходимых дополнительных библиотек  (bonzo, qwery, bean) по объёму не сильно отстаёт от jQuery. Есть ли вообще смысл не использовать jQuery?

**Comment by Diokuz** [comment]
Оно есть в тех случаях, когда на проекте уже есть заменитель, но нет jQuery. Либо когда поддерживаются только новые браузеры, и jQuery-подобная обёртка для барона будет очень лёгкой.

**Comment by Diokuz** [comment]
Fixed in baron@3.0.0
