### ISSUE TITLE
Webpack build

### ISSUE THREAD

**Issue by Diokuz** [Diokuz/baron#143]
Size of minified gzipped production version must not grow in size more than 10%.

**Comment by masterx2** [comment]
Есть вероятность что он заработает с Webpack ?

**Comment by Diokuz** [comment]
Он работает) См. https://github.com/Diokuz/baron/issues/156

**Comment by Diokuz** [comment]
Он не работает без jQuery. Будет исправлено в 3.0.

**Comment by Diokuz** [comment]
Fixed in baron@3.0.0
