### ISSUE TITLE
Wrong scroll position on field focus with height resize

### ISSUE THREAD

**Issue by iryska** [Diokuz/baron#146]
Hi @Diokuz,
We have section with fields and scroll. Last item in this section textarea. once user type more than 1 line of text in this textarea, height of textarea and whole section increased. Scroll also increased but stay at the middle on section, so user should remove focus and scroll bottom.
Maybe plugin have something that will help us scroll to the bottom of the section when we change height of textarea? I didn't find it in settings.

Thanks

**Comment by Diokuz** [comment]
Good testcase!

No, there is no 'textarea'-option.

There is a default browser-behaviour:

![1](https://cloud.githubusercontent.com/assets/2929442/14788525/f30c0e30-0b10-11e6-9393-f291ed3f7ad4.gif)

I suppose you use some js-code to make textarea bigger? If so, you need to set `scrollTop` value of `scroller` html-node equal to `scrollHeight`, or just big enough (9999 for example) after the textarea height has changed.

Baron did not set scroll position at all (that is the philosophy of baron), it just paint some things, like custom scrollbar.

**Comment by Diokuz** [comment]
Does the problem disappear after disabling baron? It should stay. I mean, it is not a baron-problem, I suppose.

**Comment by iryska** [comment]
thanks, found solution - scroll via js once height changed
