### ISSUE TITLE
Инициализация переменной scopedBaron

### ISSUE THREAD

**Issue by vykulakov** [Diokuz/baron#148]
В файле https://github.com/Diokuz/baron/blob/master/src/autoUpdate.js желательно явно инициализировать переменную scopedBaron по аналогии с другими модулями (например, https://github.com/Diokuz/baron/blob/master/src/fix.js). В противном случае в некоторых сценариях использования инициализация барона крашится.

**Comment by Diokuz** [comment]
ой)

**Comment by Diokuz** [comment]
https://github.com/Diokuz/baron/commit/28452ccc61cf5969f5a34095548bd7b50d8c8b7b

**Comment by vykulakov** [comment]
Спасибо!
