### ISSUE TITLE
Uncaught TypeError: (intermediate value) is not a function

### ISSUE THREAD

**Issue by mis-antonova** [Diokuz/baron#153]
Hi @Diokuz,
I was trying to use baron in my project and I'm getting this error: 
`baron.js:936 Uncaught TypeError: (intermediate value)(...) is not a function`

**Comment by Diokuz** [comment]
Wow, thats interesting!
Can you please tell how exactly you get this error, and browser in which you get it?

**Comment by Diokuz** [comment]
Problem: http://stackoverflow.com/questions/23370269/jquery-autosize-plugin-error-intermediate-value-is-not-a-function
fixed

**Comment by Diokuz** [comment]
@mis-antonova thank you!
