### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by edDimensi** [Diokuz/baron#156]
Пытался вставить в проект ваш плагин.
Никак не получается импортировать.
Делаю
```
import 'baron';

$(document).ready(() => {
	$('.updating').baron();
});
```
Получаю: `jquery.js:3846 jQuery.Deferred exception: $(...).baron is not a function TypeError: $(...).baron is not a function`

Делаю
```
import baron from 'baron';

const scroller = baron.noConfict();

$('updating').scroller();
```
Получаю: `Uncaught TypeError: _baron2.default.noConfict is not a function`

Делаю:
```
baron({
	scroller: '.updating'
});
```
Получаю: `Uncaught TypeError: Cannot read property 'apply' of undefined`
![image](https://cloud.githubusercontent.com/assets/11390039/21628820/7beb14dc-d233-11e6-98dc-1f08eefe0222.png)

В вебпак я прокинул все виды jquery которые только можно:
```
		new webpack.ProvidePlugin({
			$: 'jquery',
			jQuery: 'jquery',
			'window.jQuery': 'jquery',
			'window.$': 'jquery'
		})
```

Как правильно подключить его? Заранее спасибо.
Пытался подключить продакшен версию барона, а он вебпак зачем-то начинает искать файлы ./core и т.д.

**Comment by mk-initflow** [comment]
@edDimensi Получилось запустить с вебпаком его?

**Comment by Diokuz** [comment]
Всё просто: если baron используется как CommonJS module, то он не пытается встроиться как plugin jQuery.

```
import baron from 'baron'

$(document).ready(() => {
    baron(...)
})
```

thats it.

Сейчас добавлю тесткейс в папку `/test/webpack` и описание в `readme.md`.
