### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by Badalik** [Diokuz/baron#158]
Использую сборку с webpack, после апдейта появилась ошибка Cannot read property 'apply' of undefined, до этого стояла версия 2.2.2
![baron](https://cloud.githubusercontent.com/assets/5966413/22175268/c49744c6-e002-11e6-9211-bbc17cbea572.png)

**Comment by mk-initflow** [comment]
@Badalik Получилось запустить с вебпаком его?

**Comment by Badalik** [comment]
@mk-initflow нет, только с версией 2.2.2

**Comment by Diokuz** [comment]
@Badalik как вы его запускаете, как jQuery плагин? Тогда см. https://github.com/Diokuz/baron/issues/156

**Comment by edDimensi** [comment]
![image](https://user-images.githubusercontent.com/11390039/29898084-9e55ced4-8dec-11e7-86ae-468398993041.png)
Подключаю вот так.
```
  import baron from 'baron';

  function mounted() {
    const contentElement = this.$refs.content;

    baron(contentElement);
  }
```

this.$refs.content ссылка на обычный dom элемент.

**Comment by Diokuz** [comment]
Ох, обленился я совсем :(
Обещаю починить на следующей неделе, если воспроизведу. Но идея почему сломано уже есть.

**Comment by edDimensi** [comment]
@Diokuz, проблема ясна как день.
Ваш логгер пытается выдать инфу, что барон подключили, но jquery он не находит, но что-то идет не так и сам логгер падает.
Проблема в доке, у вас сказано, что baron якобы не зависим от jquery и может вполне себе работать, а оказывается нужно портянку функций или кучу библиотек подключить, чтоб заменить этот jquery. И я не могу понять, как так, написано, что jquery не нужен, но без jquery не пашет.

**Comment by berrtech** [comment]
C jquery тоже падает если вебпаком подключать. Если я правильно понял, проблема здесь, в` core.js`

![image](https://user-images.githubusercontent.com/12111256/29925473-18501d9e-8e69-11e7-82ba-c5b9c9de3443.png)

`baron.fn.log` определяеться в `debug.js`, но в `core.js` он нигде не подключается, соответственно здесь при логгинге и получаем `apply of undefined`

![image](https://user-images.githubusercontent.com/12111256/29925557-515e26b2-8e69-11e7-8eeb-2338b0a7c632.png)

**Comment by Diokuz** [comment]
Ха!

Да, здесь сразу две проблемы

1. Не передан или определён в глобале jQeury или его заменитель. Я понимаю, что это проблема распространённая, поскольку мало кто к реакту лепит jQuery, но починка потребует времени.
2. Сломано логирование, потому что при сборке вебпаком подцепляется не минифицированная продакшн-версия, а исходники. Это я починю быстро, но большинство кейсов это не починет.

В общем, in progress...

Workaround: just add jQuery to your webapp.

**Comment by Diokuz** [comment]
Fixed in baron@3.0.0
