### ISSUE TITLE
Отловить изменения размера скролла.

### ISSUE THREAD

**Issue by Nivelium** [Diokuz/baron#159]
Добрый день!
Как отловить момент, когда размер скролла изменился в результате триггера события sizeChange?

**Comment by Diokuz** [comment]
Событие `sizeChange` само по себе никогда не происходит) Это кастомное событие, которое можно бросить в HTMLElement с целью, чтоб барон обновился. При наличии autoUpdate, обработки window.onresize и возможности ручного update(), опция кажется лишней, и возможно её пора выпилить)

Изначально событие было сделано для случаев, когда доступ к инстансу барона по каким-то причинам затруднён, а автоматическое обновление почему-то не работает.
