### ISSUE TITLE
Horizontal scroll by mousewheel

### ISSUE THREAD

**Issue by serjazz** [Diokuz/baron#164]
Good day.
If this is possible: scrolling with the mouse wheel at horizontal placement. Currently, the scrolling works only if it is explicitly pulling the slider: http://take.ms/r8b1A 

When I try to scroll while over the element - turns page.

**Comment by serjazz** [comment]
Так же интересует момент возможности прокрутки горизонтального содержимого по touch

**Comment by lovelyelfpop** [comment]
English please, most of us are not familiar with Russian

**Comment by serjazz** [comment]
I`m change my comments into english.
