### ISSUE TITLE
Прокрутка в Edge

### ISSUE THREAD

**Issue by Filthyk** [Diokuz/baron#166]
Не видно скроллбара в Edge и scrolltop не изменяется при прокрутке

**Comment by Diokuz** [comment]
Посмотрел в крайнем edge на win10, никаких проблем не заметил на [демо-странице](http://diokuz.github.io/baron/).

@Filthyk у тебя проблемы на демке проявляются? Если нет, можешь сделать тесткейс где-нибудь в jsfiddle?

**Comment by Filthyk** [comment]
Проблема была, т.к. навешивал на body скроллер, перевесил на блок и всё завелось)

**Comment by Diokuz** [comment]
Так точно) Он должен был в консоль про это ругаться

https://github.com/Diokuz/baron/blob/master/docs/logs/do-not-use-body.md

Похоже проблема не только в вебкитах.
