### ISSUE TITLE
Не пойму, как его инициализировать?

### ISSUE THREAD

**Issue by Safe-Mode** [Diokuz/baron#168]
Класс чего задавать при передаче в baron('.my-scroller'); Jquery не нужен?
Ошибка такая из-за чего может быть?

![error](https://user-images.githubusercontent.com/20503101/33167308-2e371af0-d04e-11e7-81e4-1bb8891058d4.jpg)

**Comment by Diokuz** [comment]
Привет)

На данный момент строки не поддерживаются https://github.com/Diokuz/baron/blob/master/docs/api.md
Наверное, стоит их добавить.

Попробуй так:

```
baron({ scroller: '.my-scroller' })
```

**Comment by Diokuz** [comment]
Fixed in `baron@3.0.3`
