### ISSUE TITLE
Как поменять настройки по умолчанию?

### ISSUE THREAD

**Issue by nicothin** [Diokuz/baron#173]
Использую несколько вызовов:
```
baron({
    root: '.baron--block-demo',
    scroller: '.baron__scroller',
    bar: '.baron__bar',
    scrollingCls: 'baron--scrolling',
    draggingCls: 'baron--dragging',
    barOnCls: 'baron--scrollbar',
  });
baron({
    root: '.promo__demo',
    scroller: '.baron__scroller',
    bar: '.baron__bar',
    scrollingCls: 'baron--scrolling',
    draggingCls: 'baron--dragging',
    barOnCls: 'baron--scrollbar',
  });
...
```
В них отличаются только строки с `root`
Можно ли как-то задать прочие настройки один раз, чтобы не дублировать их, но иметь возможность поменять для какого-то конкретного селектора, если понадобится?

**Comment by rustam87** [comment]
А что мешает в цикле прокрутить инициализацию где в root добавить переменную

**Comment by Diokuz** [comment]
Дефолтные настройки добавляют сложности использования. Как вариант, можно сделать обёртку над бароном, которая будет вызывать барон с дефолтными параметрами:
```js
function baronWrapper(params) {
  return baron({ ...defaultParams, ...params })
}
```
