### ISSUE TITLE
Scroll track не обновляется при скролле

### ISSUE THREAD

**Issue by korenb** [Diokuz/baron#175]
Привет!

В общем, я заюзал baron, но почему то не работает barOnCls и не обновляется inline-стили на track-bar элементе. (его размеры: top и height)
https://jsfiddle.net/korenb/g81db902/
В чём может быть причина? Что не так делаю?

используется baron@3.0.3

**Comment by Diokuz** [comment]
Привет)
Две ошибки
1. Скроллился body а не scroller. Нужно чтоб скроллер был ограничен по высоте.
2. В barOnCls не нужна точка первым символом, это просто класс, а не селектор

Исправленный вариант https://jsfiddle.net/g81db902/6/
