### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by nicothin** [Diokuz/baron#176]
Использую baron на проекте, беру в сборку `node_modules/baron/baron.min.js`, к странице подключен один JS-файл, в который конкатенируются несколько JS-файлов.
Если baron в такой сборке есть, но на странице нет блоков с кастомным скроллом, то в консоли браузера:
```
Uncaught TypeError: Cannot read property 'getAttribute' of null
```

**Comment by Diokuz** [comment]
Судя по всему, проблема в том, что `baron` всё равно вызывается, хотя dom элемента, на котором ему нужно инициализироваться — нет.

В _не min_ сборке (её рекомендуется использовать в режиме разработки) была бы вот такая ошибка:

<img width="644" alt="2018-02-18 10 49 15" src="https://user-images.githubusercontent.com/2929442/36349505-8bf6505e-1499-11e8-84a0-695c55b27e8d.png">

Решение: вызывать baron только тогда, когда блок с кастомным скроллом появляется на странице.

Если проблема в другом, то нужно больше информации)
