### ISSUE TITLE
Залипание прокрутки

### ISSUE THREAD

**Issue by fasnet** [Diokuz/baron#183]
В модальном окне есть область с прокручиванием, для нее использую baron. Работает отлично. Если модальное окно уменьшить в размерах до такой степени, чтобы оно перестало помещаться по высоте на странице, появляется дефолтный скролл модального окна. Все ок, так и должно быть. Но проблема в том, что если прокрутить скролл модального окна, а потом начать скролировать область с прокручиванием с использованием baron, то скролл baron залипает, а прокручивается дефолтный скролл всего модального окна

Такую проблему встречаю в Safari.

Update: Смотрю метод manageEvents, в нем onScroll не всегда отрабатывает

**Comment by fasnet** [comment]
Нашел решение. При скролле всего модального окна вызываю scroller.update() - вроде помогло избавиться от проблемы несрабатывания скролла.

**Comment by Diokuz** [comment]
Судя по описанию, у тебя там два скролла получилось. Один из них нужно убрать.
