### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by ivarnavsky** [Diokuz/baron#60]
Планируется ли добавить поддержку RTL?

**Comment by Diokuz** [comment]
В этом кейсе скроллбар располагается с другой стороны, но к каким багам это приводит я пока не понимаю.

В будущем я хочу сделать второй режим: не через ширину, а через абсолютное позиционирование и отступы.

Если есть другие баги, готов обсудить.

**Comment by Diokuz** [comment]
Fixed for clipper cross scroll case
