### ISSUE TITLE
headers fixed outside viewport

### ISSUE THREAD

**Issue by halyvin** [Diokuz/baron#68]
ENG: Headers fixed outside viewport don't  sets bottom value and don't sets fixing mod.

RUS: Фиксированным заголовкам, что за пределами  вьюпорта браузера не проставляются css-значение bottom и не выставляется модификатор фиксирования заголовка.

**Comment by Diokuz** [comment]
Что характерно, таска где это критично ещё не вышла))
Но суть проблемы в том, что браузер не рассчитывает координаты и размеры очень далеко расположенных элементов.

**Comment by halyvin** [comment]
Дима, таска уже стухла :)

**Comment by Diokuz** [comment]
Прилипающих заголовков в 3.0 не будет.
