### ISSUE TITLE
Разбаронивание модуля плохо работает.

### ISSUE THREAD

**Issue by halyvin** [Diokuz/baron#70]
http://2gis.ru/moscow/search/29%20%D0%B8%D1%81%D1%82%D1%80%D0%B0/route/4504205217761005/center/36.736908%2C55.904672/tab/transport/zoom/12/rsType/subway

При уменьшении высоты вьюпорта (и в тот момент, когда барон должен перестать работать) не сниматются модификаторы _state_fixed и для верхнего заголовка _outside.

**Comment by Diokuz** [comment]
В 3.0 не будет заголовков.
