### ISSUE TITLE
ошибка при повторной инициализации

### ISSUE THREAD

**Issue by PankovAlxndr** [Diokuz/baron#81]

**Comment by Diokuz** [comment]
Надо чтоб при втором и последующих показах не вызывался код инициализации барона.
можно тупо обернуть её в try catch

Я согласен, что ошибку бросать не надо, достаточно будет console.warn
поправлю в следующей итерации

**Comment by PankovAlxndr** [comment]
Ага, а как проверить, что он был уже инициализирован? Можно примерчик?
