### ISSUE TITLE
Изменяется высота родителя при наведении на скролл

### ISSUE THREAD

**Issue by max-mykhailenko** [Diokuz/baron#82]
Видео http://quick.as/lq4gtbxx . Непонятно когда может быть такое поведение. В примере demo разные вложенности для вертикального и горизонтального `.scroller__track`. Пробовал оба варианта, поведение идентичное.

**Comment by max-mykhailenko** [comment]
Так же высота изменятся при изменении размеров окна браузера

**Comment by max-mykhailenko** [comment]
Происходит, когда на track есть css transition

**Comment by Diokuz** [comment]
Недавно был добавлен параметр `impact`, поставь его в значение `clipper`. Это приведёт к тому, что высота будет выставляться клипперу (родителю скроллера). В этом случае у скроллера должна быть определена высота (либо через css, либо контентом), иначе он будет поджиматься при каждом апдейте, и ситуация превратится в прямо противоположную.
