### ISSUE TITLE
Nested scrollers

### ISSUE THREAD

**Issue by leosdad** [Diokuz/baron#87]
Hi, I'm trying to use Baron to replace the stock scrollbars in my website and I'm enjoying its simplicity. However I need nested scrollable elements, e.g. a textarea inside a large scrollable div. I couldn't make both scrollers work no matter what.

Is there any way this can be achieved? Would you please post some sample HTML?

Hope you can help. Thanks in advance!

**Comment by Diokuz** [comment]
Hi there. Sorry for late answer.

Baron *do* support nested scrollers. You just need to set proper options, particularly `scroller` and `clipper`.

If you still have problems, please, post you code (html and js).
