### ISSUE TITLE
Touchpad scroll problem in Firefox

### ISSUE THREAD

**Issue by lyk0rian** [Diokuz/baron#93]
Демонстрация бага на видео: http://www.youtube.com/watch?v=yE5X7wnN2Jo

Почему-то в firefox'е не убираются стандартные scroll'ы.

Баг проявляется если пользоваться touchpad'ом в момент инициализации. Для чистоты эксперимента на том же самом компьютере пробовал повторить ситуацию на видео с использованием мышки. Не получилось.

Если мышкой нажимаем "reload", ждем пока загрузится страничка, после этого двигаем скроллы хоть колесиком, хоть touchpad'ом, ситуацию на видео повторить не удастся. Отключаем мышку, обновляем страничку с помощью touchpad'а, получаем ситуацию как на видео.

Второй ролик на котором я подключал мышку: http://www.youtube.com/watch?v=VlRLUk6uPdQ

Просьба обратить внимание на 24-ю секунду ролика. В момент отключения мышки почему-то поменялось форматирование текста (запись ролика не прерывалась). После перезагрузки странички опять откуда-то появляется нативный scroll.

На webkit браузерах (chrome, safari) такой фигни не происходит. Из перечисленной тройки баг проявляется только в firefox'е.

**Comment by Diokuz** [comment]
К сожалению, firefox на mac не поддерживается из-за этого wontfix-бага:
https://bugzilla.mozilla.org/show_bug.cgi?id=926294

**Comment by andreyvolokitin** [comment]
Может можно разветвить код, сделав для FF (или даже mac ff) решение с ```padding```, тем самым не влияя на webkit? Баг FF с textarea (https://bugzilla.mozilla.org/show_bug.cgi?id=157846) вроде уже исправлен...
