### ISSUE TITLE
Барон без кастомизации скроллбара

### ISSUE THREAD

**Issue by lastw** [Diokuz/baron#95]
Барон не поддерживает FF под OS X, но это ограничение должно касаться только кастомизации скроллбара. Нужно сделать кастомизацию опциональной, чтобы можно было под FF инициализировать барон только для прилипающих заголовков, например.

**Comment by Diokuz** [comment]
Кажется, это зона ответственности не барона, а обёртки, которая отключает барон в osx ff. Можно просто включить барон обратно, но скрыть скроллбар в ff.
