### ISSUE TITLE
Пересчет высоты родителя в режиме горизонтального скролла

### ISSUE THREAD

**Issue by c1n1k** [Diokuz/baron#96]
После смены размера вьюпорта, допустим смена ориентации на планшете, элементы внутри блока scroller меняют свою высоту, задано в стилях через @media, а блок sсroller свою высоту не меняет. Метод update почему-то не помогает, и триггер тоже

**Comment by Diokuz** [comment]
Не совсем понял проблему. Scroller не меняет высоту, но должен её менять? Скролл вертикальный?

Можешь пример сделать на jsfiddle.com?
Или, хотя бы, привести код инициализации барона?

**Comment by c1n1k** [comment]
var scrollNews = $('#article').baron({
		scroller: '.scroller',
		root: $('.article__list'),
		bar: '.scroller__bar',
		track: '.scroller__track',
		barOnCls: 'baron_h',
		freeze: true,
		direction: 'h'
	});

У меня есть блок-родитель, который прокручивается по горизонтали, в нём ещё блоки-потомки, у этих потомков есть картинка и есть блок текста описания. На разрешении в 480px у потомков, описание находится справа от картинки, на разрешении в 320 под картинкой. Получается если экран в 480px, то высота потомка 150px, если экран 320px то высота потомка 300px. 
Так вот проблема в том, что при смене ориентации с 320 на 480 высота родителя остается прежней в 300px и образуется пространство

**Comment by Diokuz** [comment]
Понял.
Да, это баг, связанный с починкой другого https://github.com/Diokuz/baron/blob/master/src/core.js#L536
Посмотрю.

**Comment by Diokuz** [comment]
Попробуй вот эту версию https://github.com/Diokuz/baron/blob/rework-horizontal-freeze/baron.js

**Comment by c1n1k** [comment]
Работает:)))

**Comment by Diokuz** [comment]
fixed https://github.com/Diokuz/baron/pull/97

**Comment by c1n1k** [comment]
Только скролл не скрывается:)

**Comment by c1n1k** [comment]
только всплыл небольшой баг, браузерный скролл не скрывается

**Comment by Diokuz** [comment]
Хм...

1. Убедись, что клипперу (ноде, являющейся прямым родителем скроллера - элемента, у которого появляется скроллбар) инлайново выставилась высота (это делает барон).
2. Убедись, что высота скроллера: 1) либо зависит только от контента (нет, например, height: 100%) 2) либо задана жёстко через CSS. В любом случае, высота скроллера *не должна зависеть от высоты клиппера*.

Если баг не пройдёт, будем смотреть дальше) Но должен пройти.

**Comment by c1n1k** [comment]
1. выставилось инлайново
2. 1. высоту в стилях не указываю 2. если указываю то браузерный скролл накладывается на сэмулированный

**Comment by c1n1k** [comment]
а есть возможность отключить baron? что-то подобное destroy?

**Comment by c1n1k** [comment]
вылез новый баг — если нужно применить к 2-м элементам барон, то для второго инициализация не происходит

**Comment by Diokuz** [comment]
Баг посмотрю.

Отключить барон?) Можно просто не инициализировать)

**Comment by c1n1k** [comment]
а как отменить инициализацию, допустим при смене размера вьюпорта
